[build]
  command = "ng build --configuration=production"
  publish = "dist/popcorn-hub"

[[plugins]]
  package = "@netlify/angular-runtime"
  [plugins.inputs]
    enabled = false
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
